spring:
  pulsar:
    client:
      service-url: pulsar://localhost:6650
  cloud:
    function:
      definition: testListener
    stream:
      bindings:
        testListener-in-0:
          destination: test
          consumer:
            use-native-decoding: true

      pulsar:
        bindings:
          testListener-in-0:
            consumer:
              subscription-type: Shared
              negative-ack-redelivery-delay: 1s
              dead-letter-policy:
                dead-letter-topic: notification-dlq
                max-redeliver-count: 5
              schema-type: JSON
              message-type: global.din.pulsartest.PulsarTestApplication.TestMessage


server:
  port: 8081
